export default function teamSelector() {

const userTeam = {
  "team": "Team 1",
  "players": [
    {
      "role": "PG",
      "player": "Dana Barros",
      "season": "1994-95",
      "age": 27,
      "team": "PHI",
      "league": "NBA",
      "position": "PG",
      "games": 82,
      "games_started": 82,
      "minutes_played": 3318,
      "field_goals": 571,
      "field_goal_attempts": 1165,
      "field_goal_percentage": 0.49,
      "three_pointers": 197,
      "free_throws": 347,
      "free_throw_attempts": 386,
      "free_throw_percentage": 0.899,
      "total_rebounds": 274,
      "assists": 619,
      "steals": 149,
      "blocks": 4,
      "turnovers": 242,
      "points": 1686
    },
    {
      "role": "SG",
      "player": "Michael Jordan",
      "season": "1988-89",
      "age": 25,
      "team": "CHI",
      "league": "NBA",
      "position": "SG",
      "games": 81,
      "games_started": 81,
      "minutes_played": 3255,
      "field_goals": 966,
      "field_goal_attempts": 1795,
      "field_goal_percentage": 0.538,
      "three_pointers": 27,
      "free_throws": 674,
      "free_throw_attempts": 793,
      "free_throw_percentage": 0.85,
      "total_rebounds": 652,
      "assists": 650,
      "steals": 234,
      "blocks": 65,
      "turnovers": 290,
      "points": 2633
    },
    {
      "role": "SF",
      "player": "Andre Iguodala",
      "season": "2007-08",
      "age": 24,
      "team": "PHI",
      "league": "NBA",
      "position": "SF",
      "games": 82,
      "games_started": 82,
      "minutes_played": 3242,
      "field_goals": 582,
      "field_goal_attempts": 1277,
      "field_goal_percentage": 0.456,
      "three_pointers": 101,
      "free_throws": 365,
      "free_throw_attempts": 506,
      "free_throw_percentage": 0.721,
      "total_rebounds": 446,
      "assists": 391,
      "steals": 171,
      "blocks": 49,
      "turnovers": 214,
      "points": 1630
    },
    {
      "role": "PF",
      "player": "Kevin Willis",
      "season": "1991-92",
      "age": 29,
      "team": "ATL",
      "league": "NBA",
      "position": "PF",
      "games": 81,
      "games_started": 80,
      "minutes_played": 2962,
      "field_goals": 591,
      "field_goal_attempts": 1224,
      "field_goal_percentage": 0.483,
      "three_pointers": 6,
      "free_throws": 292,
      "free_throw_attempts": 363,
      "free_throw_percentage": 0.804,
      "total_rebounds": 1258,
      "assists": 173,
      "steals": 72,
      "blocks": 54,
      "turnovers": 197,
      "points": 1480
    },
    {
      "role": "C",
      "player": "Tom Owens",
      "season": "1978-79",
      "age": 29,
      "team": "POR",
      "league": "NBA",
      "position": "C",
      "games": 82,
      "games_started": null,
      "minutes_played": 2791,
      "field_goals": 600,
      "field_goal_attempts": 1095,
      "field_goal_percentage": 0.548,
      "three_pointers": null,
      "free_throws": 320,
      "free_throw_attempts": 403,
      "free_throw_percentage": 0.794,
      "total_rebounds": 740,
      "assists": 301,
      "steals": 59,
      "blocks": 58,
      "turnovers": 247,
      "points": 1520
    }
  ]
}

const opponent = {
  "team": "Team 2",
  "players": [
    {
      "role": "PG",
      "player": "Michael Williams",
      "season": "1991-92",
      "age": 25,
      "team": "IND",
      "league": "NBA",
      "position": "PG",
      "games": 79,
      "games_started": 76,
      "minutes_played": 2750,
      "field_goals": 404,
      "field_goal_attempts": 824,
      "field_goal_percentage": 0.49,
      "three_pointers": 8,
      "free_throws": 372,
      "free_throw_attempts": 427,
      "free_throw_percentage": 0.871,
      "total_rebounds": 282,
      "assists": 647,
      "steals": 233,
      "blocks": 22,
      "turnovers": 240,
      "points": 1188
    },
    {
      "role": "SG",
      "player": "Jeff Hornacek",
      "season": "1991-92",
      "age": 28,
      "team": "PHO",
      "league": "NBA",
      "position": "SG",
      "games": 81,
      "games_started": 81,
      "minutes_played": 3078,
      "field_goals": 635,
      "field_goal_attempts": 1240,
      "field_goal_percentage": 0.512,
      "three_pointers": 83,
      "free_throws": 279,
      "free_throw_attempts": 315,
      "free_throw_percentage": 0.886,
      "total_rebounds": 407,
      "assists": 411,
      "steals": 158,
      "blocks": 31,
      "turnovers": 170,
      "points": 1632
    },
    {
      "role": "SF",
      "player": "LeBron James",
      "season": "2009-10",
      "age": 25,
      "team": "CLE",
      "league": "NBA",
      "position": "SF",
      "games": 76,
      "games_started": 76,
      "minutes_played": 2966,
      "field_goals": 768,
      "field_goal_attempts": 1528,
      "field_goal_percentage": 0.503,
      "three_pointers": 129,
      "free_throws": 593,
      "free_throw_attempts": 773,
      "free_throw_percentage": 0.767,
      "total_rebounds": 554,
      "assists": 651,
      "steals": 125,
      "blocks": 77,
      "turnovers": 261,
      "points": 2258
    },
    {
      "role": "PF",
      "player": "Pascal Siakam",
      "season": "2018-19",
      "age": 24,
      "team": "TOR",
      "league": "NBA",
      "position": "PF",
      "games": 80,
      "games_started": 79,
      "minutes_played": 2548,
      "field_goals": 519,
      "field_goal_attempts": 945,
      "field_goal_percentage": 0.549,
      "three_pointers": 79,
      "free_throws": 237,
      "free_throw_attempts": 302,
      "free_throw_percentage": 0.785,
      "total_rebounds": 549,
      "assists": 248,
      "steals": 73,
      "blocks": 52,
      "turnovers": 154,
      "points": 1354
    },
    {
      "role": "C",
      "player": "Marc Gasol",
      "season": "2016-17",
      "age": 32,
      "team": "MEM",
      "league": "NBA",
      "position": "C",
      "games": 74,
      "games_started": 74,
      "minutes_played": 2531,
      "field_goals": 532,
      "field_goal_attempts": 1160,
      "field_goal_percentage": 0.459,
      "three_pointers": 104,
      "free_throws": 278,
      "free_throw_attempts": 332,
      "free_throw_percentage": 0.837,
      "total_rebounds": 464,
      "assists": 338,
      "steals": 67,
      "blocks": 99,
      "turnovers": 166,
      "points": 1446
    }
  ]
}

}